-- Generated from experiment/tech_stack_pipeline.ipynb.
-- Candidate mining output is intentionally excluded until manually approved.
BEGIN;

INSERT INTO job_role (role_code, role_name, is_analysis_target, sort_order)
VALUES
    ('GENERAL_SOFTWARE_ENGINEER', 'General Software Engineer', TRUE, 1),
    ('BACKEND_SERVER', 'Backend / Server', TRUE, 2),
    ('FRONTEND', 'Frontend', TRUE, 3),
    ('FULLSTACK', 'Full-stack', TRUE, 4),
    ('MOBILE', 'Mobile', TRUE, 5),
    ('DATA_ENGINEER_PLATFORM', 'Data Engineer / Data Platform', TRUE, 6),
    ('DATA_ANALYST', 'Data Analyst', TRUE, 7),
    ('ML_AI_DATA_SCIENTIST', 'ML / AI Engineer / Data Scientist', TRUE, 8),
    ('RESEARCH_ENGINEER_SCIENTIST', 'Research Engineer / Scientist', TRUE, 9),
    ('INFRA_PLATFORM_DEVOPS_SRE', 'Infra / Platform / DevOps / SRE', TRUE, 10),
    ('SYSTEMS_LOW_LEVEL', 'Systems / Low-level', TRUE, 11),
    ('SECURITY_ENGINEER', 'Security Engineer', TRUE, 12),
    ('SOLUTIONS_FORWARD_DEPLOYED', 'Solutions / Forward Deployed', TRUE, 13),
    ('ENGINEERING_MANAGEMENT', 'Engineering Management', TRUE, 14),
    ('OTHER_NON_DEVELOPER', 'Other / Non-Developer', FALSE, 15)
ON CONFLICT (role_code) DO UPDATE SET
    role_name = EXCLUDED.role_name,
    is_analysis_target = EXCLUDED.is_analysis_target,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE;

INSERT INTO skill_category (category_code, category_name, sort_order)
VALUES
    ('language', 'Programming Language', 1),
    ('frontend', 'Frontend', 2),
    ('backend', 'Backend', 3),
    ('database', 'Database', 4),
    ('cloud_devops', 'Cloud / DevOps', 5),
    ('data_ml', 'Data / ML', 6),
    ('mobile', 'Mobile', 7),
    ('messaging_infra', 'Messaging / Infrastructure', 8),
    ('tools', 'Tools', 9),
    ('ai_platform', 'AI Platform', 10),
    ('testing', 'Testing', 11)
ON CONFLICT (category_code) DO UPDATE SET
    category_name = EXCLUDED.category_name,
    sort_order = EXCLUDED.sort_order,
    is_active = TRUE;

INSERT INTO skill (skill_code, skill_name)
VALUES
    ('PYTHON', 'Python'),
    ('JAVA', 'Java'),
    ('JAVASCRIPT', 'JavaScript'),
    ('TYPESCRIPT', 'TypeScript'),
    ('GO_LANGUAGE', 'Go'),
    ('RUST', 'Rust'),
    ('CPP', 'C++'),
    ('CSHARP', 'C#'),
    ('C_LANGUAGE', 'C'),
    ('RUBY', 'Ruby'),
    ('PHP', 'PHP'),
    ('SWIFT', 'Swift'),
    ('KOTLIN', 'Kotlin'),
    ('SCALA', 'Scala'),
    ('R_LANGUAGE', 'R'),
    ('OBJECTIVE_C', 'Objective-C'),
    ('DART', 'Dart'),
    ('ELIXIR', 'Elixir'),
    ('ERLANG', 'Erlang'),
    ('HASKELL', 'Haskell'),
    ('PERL', 'Perl'),
    ('MATLAB', 'MATLAB'),
    ('SQL', 'SQL'),
    ('BASH', 'Bash'),
    ('JULIA', 'Julia'),
    ('GROOVY', 'Groovy'),
    ('LUA', 'Lua'),
    ('SOLIDITY', 'Solidity'),
    ('D_LANGUAGE', 'D'),
    ('REACT', 'React'),
    ('ANGULAR', 'Angular'),
    ('VUE_JS', 'Vue.js'),
    ('SVELTE', 'Svelte'),
    ('NEXT_JS', 'Next.js'),
    ('NUXT_JS', 'Nuxt.js'),
    ('JQUERY', 'jQuery'),
    ('REDUX', 'Redux'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('SASS', 'Sass'),
    ('TAILWIND_CSS', 'Tailwind CSS'),
    ('WEBPACK', 'Webpack'),
    ('VITE', 'Vite'),
    ('EMBER_JS', 'Ember.js'),
    ('BACKBONE_JS', 'Backbone.js'),
    ('D3_JS', 'D3.js'),
    ('STORYBOOK', 'Storybook'),
    ('NODE_JS', 'Node.js'),
    ('EXPRESS', 'Express'),
    ('DJANGO', 'Django'),
    ('FLASK', 'Flask'),
    ('FASTAPI', 'FastAPI'),
    ('SPRING', 'Spring'),
    ('RUBY_ON_RAILS', 'Ruby on Rails'),
    ('LARAVEL', 'Laravel'),
    ('DOTNET', '.NET'),
    ('NESTJS', 'NestJS'),
    ('GRPC', 'gRPC'),
    ('GRAPHQL', 'GraphQL'),
    ('REST', 'REST'),
    ('POSTGRESQL', 'PostgreSQL'),
    ('MYSQL', 'MySQL'),
    ('MONGODB', 'MongoDB'),
    ('REDIS', 'Redis'),
    ('CASSANDRA', 'Cassandra'),
    ('DYNAMODB', 'DynamoDB'),
    ('ELASTICSEARCH', 'Elasticsearch'),
    ('SQLITE', 'SQLite'),
    ('ORACLE_DB', 'Oracle DB'),
    ('MARIADB', 'MariaDB'),
    ('SNOWFLAKE', 'Snowflake'),
    ('BIGQUERY', 'BigQuery'),
    ('REDSHIFT', 'Redshift'),
    ('CLICKHOUSE', 'ClickHouse'),
    ('NEO4J', 'Neo4j'),
    ('COCKROACHDB', 'CockroachDB'),
    ('FIRESTORE', 'Firestore'),
    ('MONGODB_ATLAS', 'MongoDB Atlas'),
    ('AWS', 'AWS'),
    ('GCP', 'GCP'),
    ('AZURE', 'Azure'),
    ('DOCKER', 'Docker'),
    ('KUBERNETES', 'Kubernetes'),
    ('TERRAFORM', 'Terraform'),
    ('ANSIBLE', 'Ansible'),
    ('JENKINS', 'Jenkins'),
    ('GITHUB_ACTIONS', 'GitHub Actions'),
    ('GITLAB_CI', 'GitLab CI'),
    ('CIRCLECI', 'CircleCI'),
    ('HELM', 'Helm'),
    ('ISTIO', 'Istio'),
    ('PROMETHEUS', 'Prometheus'),
    ('GRAFANA', 'Grafana'),
    ('DATADOG', 'Datadog'),
    ('NGINX', 'Nginx'),
    ('LINUX', 'Linux'),
    ('CLOUDFLARE', 'Cloudflare'),
    ('VAULT', 'Vault'),
    ('OPENTELEMETRY', 'OpenTelemetry'),
    ('AWS_CLOUDFORMATION', 'AWS CloudFormation'),
    ('AMAZON_EKS', 'Amazon EKS'),
    ('GOOGLE_GKE', 'Google GKE'),
    ('AMAZON_EC2', 'Amazon EC2'),
    ('AMAZON_S3', 'Amazon S3'),
    ('ARGOCD', 'ArgoCD'),
    ('BUILDKITE', 'Buildkite'),
    ('OPENSHIFT', 'OpenShift'),
    ('PULUMI', 'Pulumi'),
    ('DEPENDABOT', 'Dependabot'),
    ('PUPPET', 'Puppet'),
    ('SNYK', 'Snyk'),
    ('OKTA', 'Okta'),
    ('SPLUNK', 'Splunk'),
    ('WEBASSEMBLY', 'WebAssembly'),
    ('TENSORFLOW', 'TensorFlow'),
    ('PYTORCH', 'PyTorch'),
    ('KERAS', 'Keras'),
    ('SCIKIT_LEARN', 'scikit-learn'),
    ('PANDAS', 'Pandas'),
    ('NUMPY', 'NumPy'),
    ('APACHE_SPARK', 'Apache Spark'),
    ('HADOOP', 'Hadoop'),
    ('APACHE_KAFKA', 'Apache Kafka'),
    ('AIRFLOW', 'Airflow'),
    ('DBT', 'dbt'),
    ('DATABRICKS', 'Databricks'),
    ('JUPYTER', 'Jupyter'),
    ('HUGGING_FACE', 'Hugging Face'),
    ('TRANSFORMERS', 'Transformers'),
    ('LANGCHAIN', 'LangChain'),
    ('OPENCV', 'OpenCV'),
    ('MLFLOW', 'MLflow'),
    ('XGBOOST', 'XGBoost'),
    ('LIGHTGBM', 'LightGBM'),
    ('TABLEAU', 'Tableau'),
    ('POWER_BI', 'Power BI'),
    ('LOOKER', 'Looker'),
    ('APACHE_FLINK', 'Apache Flink'),
    ('APACHE_ICEBERG', 'Apache Iceberg'),
    ('TRINO', 'Trino'),
    ('DAGSTER', 'Dagster'),
    ('VERTEX_AI', 'Vertex AI'),
    ('TRITON_INFERENCE_SERVER', 'Triton Inference Server'),
    ('JAX', 'JAX'),
    ('CUDA', 'CUDA'),
    ('NCCL', 'NCCL'),
    ('GITHUB_COPILOT', 'GitHub Copilot'),
    ('OPENAI_CODEX', 'OpenAI Codex'),
    ('MCP', 'MCP'),
    ('SLURM', 'Slurm'),
    ('BAZEL', 'Bazel'),
    ('GRADLE', 'Gradle'),
    ('IOS', 'iOS'),
    ('ANDROID', 'Android'),
    ('REACT_NATIVE', 'React Native'),
    ('FLUTTER', 'Flutter'),
    ('SWIFTUI', 'SwiftUI'),
    ('XAMARIN', 'Xamarin'),
    ('JETPACK_COMPOSE', 'Jetpack Compose'),
    ('RABBITMQ', 'RabbitMQ'),
    ('APACHE_PULSAR', 'Apache Pulsar'),
    ('ZOOKEEPER', 'Zookeeper'),
    ('GIT', 'Git'),
    ('GITHUB', 'GitHub'),
    ('GITLAB', 'GitLab'),
    ('JIRA', 'Jira'),
    ('FIGMA', 'Figma'),
    ('POSTMAN', 'Postman'),
    ('CONFLUENCE', 'Confluence'),
    ('SALESFORCE', 'Salesforce'),
    ('HUBSPOT', 'HubSpot'),
    ('ZENDESK', 'Zendesk'),
    ('NETSUITE', 'NetSuite'),
    ('VANTA', 'Vanta'),
    ('OPENAI', 'OpenAI'),
    ('ANTHROPIC', 'Anthropic'),
    ('CLAUDE', 'Claude'),
    ('GPT', 'GPT'),
    ('GEMINI', 'Gemini'),
    ('LLAMA', 'Llama'),
    ('JEST', 'Jest'),
    ('PYTEST', 'PyTest'),
    ('SELENIUM', 'Selenium'),
    ('CYPRESS', 'Cypress'),
    ('JUNIT', 'JUnit')
ON CONFLICT (skill_code) DO UPDATE SET
    skill_name = EXCLUDED.skill_name,
    is_active = TRUE;

INSERT INTO skill_category_map (skill_id, skill_category_id, is_primary)
SELECT s.skill_id, c.skill_category_id, seed.is_primary
FROM (VALUES
    ('PYTHON', 'language', TRUE),
    ('JAVA', 'language', TRUE),
    ('JAVASCRIPT', 'language', TRUE),
    ('TYPESCRIPT', 'language', TRUE),
    ('GO_LANGUAGE', 'language', TRUE),
    ('RUST', 'language', TRUE),
    ('CPP', 'language', TRUE),
    ('CSHARP', 'language', TRUE),
    ('C_LANGUAGE', 'language', TRUE),
    ('RUBY', 'language', TRUE),
    ('PHP', 'language', TRUE),
    ('SWIFT', 'language', TRUE),
    ('KOTLIN', 'language', TRUE),
    ('SCALA', 'language', TRUE),
    ('R_LANGUAGE', 'language', TRUE),
    ('OBJECTIVE_C', 'language', TRUE),
    ('DART', 'language', TRUE),
    ('ELIXIR', 'language', TRUE),
    ('ERLANG', 'language', TRUE),
    ('HASKELL', 'language', TRUE),
    ('PERL', 'language', TRUE),
    ('MATLAB', 'language', TRUE),
    ('SQL', 'language', TRUE),
    ('BASH', 'language', TRUE),
    ('JULIA', 'language', TRUE),
    ('GROOVY', 'language', TRUE),
    ('LUA', 'language', TRUE),
    ('SOLIDITY', 'language', TRUE),
    ('D_LANGUAGE', 'language', TRUE),
    ('REACT', 'frontend', TRUE),
    ('ANGULAR', 'frontend', TRUE),
    ('VUE_JS', 'frontend', TRUE),
    ('SVELTE', 'frontend', TRUE),
    ('NEXT_JS', 'frontend', TRUE),
    ('NUXT_JS', 'frontend', TRUE),
    ('JQUERY', 'frontend', TRUE),
    ('REDUX', 'frontend', TRUE),
    ('HTML', 'frontend', TRUE),
    ('CSS', 'frontend', TRUE),
    ('SASS', 'frontend', TRUE),
    ('TAILWIND_CSS', 'frontend', TRUE),
    ('WEBPACK', 'frontend', TRUE),
    ('VITE', 'frontend', TRUE),
    ('EMBER_JS', 'frontend', TRUE),
    ('BACKBONE_JS', 'frontend', TRUE),
    ('D3_JS', 'frontend', TRUE),
    ('STORYBOOK', 'frontend', TRUE),
    ('NODE_JS', 'backend', TRUE),
    ('EXPRESS', 'backend', TRUE),
    ('DJANGO', 'backend', TRUE),
    ('FLASK', 'backend', TRUE),
    ('FASTAPI', 'backend', TRUE),
    ('SPRING', 'backend', TRUE),
    ('RUBY_ON_RAILS', 'backend', TRUE),
    ('LARAVEL', 'backend', TRUE),
    ('DOTNET', 'backend', TRUE),
    ('NESTJS', 'backend', TRUE),
    ('GRPC', 'backend', TRUE),
    ('GRPC', 'messaging_infra', FALSE),
    ('GRAPHQL', 'backend', TRUE),
    ('REST', 'backend', TRUE),
    ('POSTGRESQL', 'database', TRUE),
    ('MYSQL', 'database', TRUE),
    ('MONGODB', 'database', TRUE),
    ('REDIS', 'database', TRUE),
    ('CASSANDRA', 'database', TRUE),
    ('DYNAMODB', 'database', TRUE),
    ('ELASTICSEARCH', 'database', TRUE),
    ('SQLITE', 'database', TRUE),
    ('ORACLE_DB', 'database', TRUE),
    ('MARIADB', 'database', TRUE),
    ('SNOWFLAKE', 'database', TRUE),
    ('BIGQUERY', 'database', TRUE),
    ('REDSHIFT', 'database', TRUE),
    ('CLICKHOUSE', 'database', TRUE),
    ('NEO4J', 'database', TRUE),
    ('COCKROACHDB', 'database', TRUE),
    ('FIRESTORE', 'database', TRUE),
    ('MONGODB_ATLAS', 'database', TRUE),
    ('AWS', 'cloud_devops', TRUE),
    ('GCP', 'cloud_devops', TRUE),
    ('AZURE', 'cloud_devops', TRUE),
    ('DOCKER', 'cloud_devops', TRUE),
    ('KUBERNETES', 'cloud_devops', TRUE),
    ('TERRAFORM', 'cloud_devops', TRUE),
    ('ANSIBLE', 'cloud_devops', TRUE),
    ('JENKINS', 'cloud_devops', TRUE),
    ('GITHUB_ACTIONS', 'cloud_devops', TRUE),
    ('GITLAB_CI', 'cloud_devops', TRUE),
    ('CIRCLECI', 'cloud_devops', TRUE),
    ('HELM', 'cloud_devops', TRUE),
    ('ISTIO', 'cloud_devops', TRUE),
    ('PROMETHEUS', 'cloud_devops', TRUE),
    ('GRAFANA', 'cloud_devops', TRUE),
    ('DATADOG', 'cloud_devops', TRUE),
    ('NGINX', 'cloud_devops', TRUE),
    ('LINUX', 'cloud_devops', TRUE),
    ('CLOUDFLARE', 'cloud_devops', TRUE),
    ('VAULT', 'cloud_devops', TRUE),
    ('OPENTELEMETRY', 'cloud_devops', TRUE),
    ('AWS_CLOUDFORMATION', 'cloud_devops', TRUE),
    ('AMAZON_EKS', 'cloud_devops', TRUE),
    ('GOOGLE_GKE', 'cloud_devops', TRUE),
    ('AMAZON_EC2', 'cloud_devops', TRUE),
    ('AMAZON_S3', 'cloud_devops', TRUE),
    ('ARGOCD', 'cloud_devops', TRUE),
    ('BUILDKITE', 'cloud_devops', TRUE),
    ('OPENSHIFT', 'cloud_devops', TRUE),
    ('PULUMI', 'cloud_devops', TRUE),
    ('DEPENDABOT', 'cloud_devops', TRUE),
    ('PUPPET', 'cloud_devops', TRUE),
    ('SNYK', 'cloud_devops', TRUE),
    ('OKTA', 'cloud_devops', TRUE),
    ('SPLUNK', 'cloud_devops', TRUE),
    ('WEBASSEMBLY', 'cloud_devops', TRUE),
    ('TENSORFLOW', 'data_ml', TRUE),
    ('PYTORCH', 'data_ml', TRUE),
    ('KERAS', 'data_ml', TRUE),
    ('SCIKIT_LEARN', 'data_ml', TRUE),
    ('PANDAS', 'data_ml', TRUE),
    ('NUMPY', 'data_ml', TRUE),
    ('APACHE_SPARK', 'data_ml', TRUE),
    ('HADOOP', 'data_ml', TRUE),
    ('APACHE_KAFKA', 'data_ml', TRUE),
    ('AIRFLOW', 'data_ml', TRUE),
    ('DBT', 'data_ml', TRUE),
    ('DATABRICKS', 'data_ml', TRUE),
    ('JUPYTER', 'data_ml', TRUE),
    ('HUGGING_FACE', 'data_ml', TRUE),
    ('TRANSFORMERS', 'data_ml', TRUE),
    ('LANGCHAIN', 'data_ml', TRUE),
    ('OPENCV', 'data_ml', TRUE),
    ('MLFLOW', 'data_ml', TRUE),
    ('XGBOOST', 'data_ml', TRUE),
    ('LIGHTGBM', 'data_ml', TRUE),
    ('TABLEAU', 'data_ml', TRUE),
    ('POWER_BI', 'data_ml', TRUE),
    ('LOOKER', 'data_ml', TRUE),
    ('APACHE_FLINK', 'data_ml', TRUE),
    ('APACHE_ICEBERG', 'data_ml', TRUE),
    ('TRINO', 'data_ml', TRUE),
    ('DAGSTER', 'data_ml', TRUE),
    ('VERTEX_AI', 'data_ml', TRUE),
    ('TRITON_INFERENCE_SERVER', 'data_ml', TRUE),
    ('JAX', 'data_ml', TRUE),
    ('CUDA', 'data_ml', TRUE),
    ('NCCL', 'data_ml', TRUE),
    ('GITHUB_COPILOT', 'data_ml', TRUE),
    ('OPENAI_CODEX', 'data_ml', TRUE),
    ('MCP', 'data_ml', TRUE),
    ('SLURM', 'data_ml', TRUE),
    ('BAZEL', 'data_ml', TRUE),
    ('GRADLE', 'data_ml', TRUE),
    ('IOS', 'mobile', TRUE),
    ('ANDROID', 'mobile', TRUE),
    ('REACT_NATIVE', 'mobile', TRUE),
    ('FLUTTER', 'mobile', TRUE),
    ('SWIFTUI', 'mobile', TRUE),
    ('XAMARIN', 'mobile', TRUE),
    ('JETPACK_COMPOSE', 'mobile', TRUE),
    ('RABBITMQ', 'messaging_infra', TRUE),
    ('APACHE_PULSAR', 'messaging_infra', TRUE),
    ('ZOOKEEPER', 'messaging_infra', TRUE),
    ('GIT', 'tools', TRUE),
    ('GITHUB', 'tools', TRUE),
    ('GITLAB', 'tools', TRUE),
    ('JIRA', 'tools', TRUE),
    ('FIGMA', 'tools', TRUE),
    ('POSTMAN', 'tools', TRUE),
    ('CONFLUENCE', 'tools', TRUE),
    ('SALESFORCE', 'tools', TRUE),
    ('HUBSPOT', 'tools', TRUE),
    ('ZENDESK', 'tools', TRUE),
    ('NETSUITE', 'tools', TRUE),
    ('VANTA', 'tools', TRUE),
    ('OPENAI', 'ai_platform', TRUE),
    ('ANTHROPIC', 'ai_platform', TRUE),
    ('CLAUDE', 'ai_platform', TRUE),
    ('GPT', 'ai_platform', TRUE),
    ('GEMINI', 'ai_platform', TRUE),
    ('LLAMA', 'ai_platform', TRUE),
    ('JEST', 'testing', TRUE),
    ('PYTEST', 'testing', TRUE),
    ('SELENIUM', 'testing', TRUE),
    ('CYPRESS', 'testing', TRUE),
    ('JUNIT', 'testing', TRUE)
) AS seed(skill_code, category_code, is_primary)
JOIN skill s USING (skill_code)
JOIN skill_category c USING (category_code)
ON CONFLICT (skill_id, skill_category_id) DO UPDATE SET
    is_primary = EXCLUDED.is_primary;

INSERT INTO skill_alias (skill_id, alias_text, alias_normalized, match_policy)
SELECT s.skill_id, seed.alias_text, seed.alias_normalized, seed.match_policy
FROM (VALUES
    ('PYTHON', 'Python', 'python', 'normal'),
    ('JAVA', 'Java', 'java', 'normal'),
    ('JAVASCRIPT', 'JavaScript', 'javascript', 'normal'),
    ('JAVASCRIPT', 'JS', 'js', 'normal'),
    ('TYPESCRIPT', 'TypeScript', 'typescript', 'normal'),
    ('TYPESCRIPT', 'TS', 'ts', 'normal'),
    ('GO_LANGUAGE', 'Golang', 'golang', 'normal'),
    ('GO_LANGUAGE', 'Go', 'go', 'ambiguous_contextual'),
    ('RUST', 'Rust', 'rust', 'normal'),
    ('CPP', 'C++', 'c++', 'normal'),
    ('CSHARP', 'C#', 'c#', 'normal'),
    ('C_LANGUAGE', 'C', 'c', 'ambiguous_contextual'),
    ('RUBY', 'Ruby', 'ruby', 'normal'),
    ('PHP', 'PHP', 'php', 'normal'),
    ('SWIFT', 'Swift', 'swift', 'normal'),
    ('KOTLIN', 'Kotlin', 'kotlin', 'normal'),
    ('SCALA', 'Scala', 'scala', 'normal'),
    ('R_LANGUAGE', 'R', 'r', 'ambiguous_contextual'),
    ('OBJECTIVE_C', 'Objective-C', 'objective-c', 'normal'),
    ('OBJECTIVE_C', 'Objective C', 'objective c', 'normal'),
    ('OBJECTIVE_C', 'ObjC', 'objc', 'normal'),
    ('DART', 'Dart', 'dart', 'normal'),
    ('ELIXIR', 'Elixir', 'elixir', 'normal'),
    ('ERLANG', 'Erlang', 'erlang', 'normal'),
    ('HASKELL', 'Haskell', 'haskell', 'normal'),
    ('PERL', 'Perl', 'perl', 'normal'),
    ('MATLAB', 'MATLAB', 'matlab', 'normal'),
    ('SQL', 'SQL', 'sql', 'normal'),
    ('BASH', 'Bash', 'bash', 'normal'),
    ('BASH', 'Bash scripting', 'bash scripting', 'normal'),
    ('BASH', 'Shell scripting', 'shell scripting', 'normal'),
    ('JULIA', 'Julia', 'julia', 'normal'),
    ('GROOVY', 'Groovy', 'groovy', 'normal'),
    ('LUA', 'Lua', 'lua', 'normal'),
    ('SOLIDITY', 'Solidity', 'solidity', 'normal'),
    ('D_LANGUAGE', 'D', 'd', 'ambiguous_contextual'),
    ('REACT', 'React', 'react', 'normal'),
    ('REACT', 'React.js', 'react.js', 'normal'),
    ('REACT', 'ReactJS', 'reactjs', 'normal'),
    ('ANGULAR', 'Angular', 'angular', 'normal'),
    ('ANGULAR', 'AngularJS', 'angularjs', 'normal'),
    ('ANGULAR', 'Angular.js', 'angular.js', 'normal'),
    ('VUE_JS', 'Vue.js', 'vue.js', 'normal'),
    ('VUE_JS', 'Vue', 'vue', 'normal'),
    ('VUE_JS', 'VueJS', 'vuejs', 'normal'),
    ('SVELTE', 'Svelte', 'svelte', 'normal'),
    ('SVELTE', 'SvelteKit', 'sveltekit', 'normal'),
    ('NEXT_JS', 'Next.js', 'next.js', 'normal'),
    ('NEXT_JS', 'NextJS', 'nextjs', 'normal'),
    ('NUXT_JS', 'Nuxt.js', 'nuxt.js', 'normal'),
    ('NUXT_JS', 'NuxtJS', 'nuxtjs', 'normal'),
    ('JQUERY', 'jQuery', 'jquery', 'normal'),
    ('REDUX', 'Redux', 'redux', 'normal'),
    ('HTML', 'HTML', 'html', 'normal'),
    ('HTML', 'HTML5', 'html5', 'normal'),
    ('CSS', 'CSS', 'css', 'normal'),
    ('CSS', 'CSS3', 'css3', 'normal'),
    ('SASS', 'Sass', 'sass', 'normal'),
    ('SASS', 'SCSS', 'scss', 'normal'),
    ('TAILWIND_CSS', 'Tailwind CSS', 'tailwind css', 'normal'),
    ('TAILWIND_CSS', 'TailwindCSS', 'tailwindcss', 'normal'),
    ('TAILWIND_CSS', 'Tailwind', 'tailwind', 'normal'),
    ('WEBPACK', 'Webpack', 'webpack', 'normal'),
    ('VITE', 'Vite', 'vite', 'normal'),
    ('EMBER_JS', 'Ember.js', 'ember.js', 'normal'),
    ('EMBER_JS', 'EmberJS', 'emberjs', 'normal'),
    ('BACKBONE_JS', 'Backbone.js', 'backbone.js', 'normal'),
    ('BACKBONE_JS', 'BackboneJS', 'backbonejs', 'normal'),
    ('D3_JS', 'D3.js', 'd3.js', 'normal'),
    ('D3_JS', 'D3JS', 'd3js', 'normal'),
    ('STORYBOOK', 'Storybook', 'storybook', 'normal'),
    ('NODE_JS', 'Node.js', 'node.js', 'normal'),
    ('NODE_JS', 'NodeJS', 'nodejs', 'normal'),
    ('NODE_JS', 'Node', 'node', 'normal'),
    ('EXPRESS', 'Express.js', 'express.js', 'normal'),
    ('EXPRESS', 'ExpressJS', 'expressjs', 'normal'),
    ('EXPRESS', 'Express', 'express', 'normal'),
    ('DJANGO', 'Django', 'django', 'normal'),
    ('FLASK', 'Flask', 'flask', 'normal'),
    ('FASTAPI', 'FastAPI', 'fastapi', 'normal'),
    ('SPRING', 'Spring Boot', 'spring boot', 'normal'),
    ('SPRING', 'Spring Framework', 'spring framework', 'normal'),
    ('SPRING', 'SpringBoot', 'springboot', 'normal'),
    ('RUBY_ON_RAILS', 'Ruby on Rails', 'ruby on rails', 'normal'),
    ('RUBY_ON_RAILS', 'Rails', 'rails', 'normal'),
    ('LARAVEL', 'Laravel', 'laravel', 'normal'),
    ('DOTNET', '.NET', '.net', 'normal'),
    ('DOTNET', 'ASP.NET', 'asp.net', 'normal'),
    ('DOTNET', 'dotnet', 'dotnet', 'normal'),
    ('NESTJS', 'NestJS', 'nestjs', 'normal'),
    ('NESTJS', 'Nest.js', 'nest.js', 'normal'),
    ('GRPC', 'gRPC', 'grpc', 'normal'),
    ('GRAPHQL', 'GraphQL', 'graphql', 'normal'),
    ('REST', 'REST API', 'rest api', 'normal'),
    ('REST', 'RESTful', 'restful', 'normal'),
    ('POSTGRESQL', 'PostgreSQL', 'postgresql', 'normal'),
    ('POSTGRESQL', 'Postgres', 'postgres', 'normal'),
    ('MYSQL', 'MySQL', 'mysql', 'normal'),
    ('MONGODB', 'MongoDB', 'mongodb', 'normal'),
    ('MONGODB', 'Mongo', 'mongo', 'normal'),
    ('REDIS', 'Redis', 'redis', 'normal'),
    ('CASSANDRA', 'Cassandra', 'cassandra', 'normal'),
    ('DYNAMODB', 'DynamoDB', 'dynamodb', 'normal'),
    ('ELASTICSEARCH', 'Elasticsearch', 'elasticsearch', 'normal'),
    ('SQLITE', 'SQLite', 'sqlite', 'normal'),
    ('ORACLE_DB', 'Oracle Database', 'oracle database', 'normal'),
    ('ORACLE_DB', 'Oracle DB', 'oracle db', 'normal'),
    ('MARIADB', 'MariaDB', 'mariadb', 'normal'),
    ('SNOWFLAKE', 'Snowflake', 'snowflake', 'normal'),
    ('BIGQUERY', 'BigQuery', 'bigquery', 'normal'),
    ('REDSHIFT', 'Redshift', 'redshift', 'normal'),
    ('CLICKHOUSE', 'ClickHouse', 'clickhouse', 'normal'),
    ('NEO4J', 'Neo4j', 'neo4j', 'normal'),
    ('COCKROACHDB', 'CockroachDB', 'cockroachdb', 'normal'),
    ('FIRESTORE', 'Firestore', 'firestore', 'normal'),
    ('MONGODB_ATLAS', 'MongoDB Atlas', 'mongodb atlas', 'normal'),
    ('AWS', 'AWS', 'aws', 'normal'),
    ('AWS', 'Amazon Web Services', 'amazon web services', 'normal'),
    ('GCP', 'GCP', 'gcp', 'normal'),
    ('GCP', 'Google Cloud Platform', 'google cloud platform', 'normal'),
    ('GCP', 'Google Cloud', 'google cloud', 'normal'),
    ('AZURE', 'Azure', 'azure', 'normal'),
    ('AZURE', 'Microsoft Azure', 'microsoft azure', 'normal'),
    ('DOCKER', 'Docker', 'docker', 'normal'),
    ('KUBERNETES', 'Kubernetes', 'kubernetes', 'normal'),
    ('KUBERNETES', 'K8s', 'k8s', 'normal'),
    ('TERRAFORM', 'Terraform', 'terraform', 'normal'),
    ('ANSIBLE', 'Ansible', 'ansible', 'normal'),
    ('JENKINS', 'Jenkins', 'jenkins', 'normal'),
    ('GITHUB_ACTIONS', 'GitHub Actions', 'github actions', 'normal'),
    ('GITLAB_CI', 'GitLab CI', 'gitlab ci', 'normal'),
    ('GITLAB_CI', 'GitLab CI/CD', 'gitlab ci/cd', 'normal'),
    ('CIRCLECI', 'CircleCI', 'circleci', 'normal'),
    ('HELM', 'Helm', 'helm', 'normal'),
    ('ISTIO', 'Istio', 'istio', 'normal'),
    ('PROMETHEUS', 'Prometheus', 'prometheus', 'normal'),
    ('GRAFANA', 'Grafana', 'grafana', 'normal'),
    ('DATADOG', 'Datadog', 'datadog', 'normal'),
    ('NGINX', 'Nginx', 'nginx', 'normal'),
    ('LINUX', 'Linux', 'linux', 'normal'),
    ('CLOUDFLARE', 'Cloudflare', 'cloudflare', 'normal'),
    ('VAULT', 'HashiCorp Vault', 'hashicorp vault', 'normal'),
    ('VAULT', 'Vault', 'vault', 'normal'),
    ('OPENTELEMETRY', 'OpenTelemetry', 'opentelemetry', 'normal'),
    ('AWS_CLOUDFORMATION', 'CloudFormation', 'cloudformation', 'normal'),
    ('AMAZON_EKS', 'EKS', 'eks', 'normal'),
    ('AMAZON_EKS', 'Amazon EKS', 'amazon eks', 'normal'),
    ('GOOGLE_GKE', 'GKE', 'gke', 'normal'),
    ('GOOGLE_GKE', 'Google Kubernetes Engine', 'google kubernetes engine', 'normal'),
    ('AMAZON_EC2', 'EC2', 'ec2', 'normal'),
    ('AMAZON_EC2', 'Amazon EC2', 'amazon ec2', 'normal'),
    ('AMAZON_S3', 'S3', 's3', 'normal'),
    ('AMAZON_S3', 'Amazon S3', 'amazon s3', 'normal'),
    ('ARGOCD', 'ArgoCD', 'argocd', 'normal'),
    ('ARGOCD', 'Argo CD', 'argo cd', 'normal'),
    ('BUILDKITE', 'Buildkite', 'buildkite', 'normal'),
    ('OPENSHIFT', 'OpenShift', 'openshift', 'normal'),
    ('PULUMI', 'Pulumi', 'pulumi', 'normal'),
    ('DEPENDABOT', 'Dependabot', 'dependabot', 'normal'),
    ('PUPPET', 'Puppet', 'puppet', 'normal'),
    ('SNYK', 'Snyk', 'snyk', 'normal'),
    ('OKTA', 'Okta', 'okta', 'normal'),
    ('SPLUNK', 'Splunk', 'splunk', 'normal'),
    ('WEBASSEMBLY', 'WebAssembly', 'webassembly', 'normal'),
    ('WEBASSEMBLY', 'Wasm', 'wasm', 'normal'),
    ('TENSORFLOW', 'TensorFlow', 'tensorflow', 'normal'),
    ('PYTORCH', 'PyTorch', 'pytorch', 'normal'),
    ('KERAS', 'Keras', 'keras', 'normal'),
    ('SCIKIT_LEARN', 'scikit-learn', 'scikit-learn', 'normal'),
    ('SCIKIT_LEARN', 'sklearn', 'sklearn', 'normal'),
    ('PANDAS', 'Pandas', 'pandas', 'normal'),
    ('NUMPY', 'NumPy', 'numpy', 'normal'),
    ('APACHE_SPARK', 'Apache Spark', 'apache spark', 'normal'),
    ('APACHE_SPARK', 'Spark', 'spark', 'normal'),
    ('APACHE_SPARK', 'PySpark', 'pyspark', 'normal'),
    ('HADOOP', 'Hadoop', 'hadoop', 'normal'),
    ('APACHE_KAFKA', 'Apache Kafka', 'apache kafka', 'normal'),
    ('APACHE_KAFKA', 'Kafka', 'kafka', 'normal'),
    ('AIRFLOW', 'Airflow', 'airflow', 'normal'),
    ('AIRFLOW', 'Apache Airflow', 'apache airflow', 'normal'),
    ('DBT', 'dbt', 'dbt', 'normal'),
    ('DATABRICKS', 'Databricks', 'databricks', 'normal'),
    ('JUPYTER', 'Jupyter', 'jupyter', 'normal'),
    ('JUPYTER', 'Jupyter Notebook', 'jupyter notebook', 'normal'),
    ('HUGGING_FACE', 'Hugging Face', 'hugging face', 'normal'),
    ('HUGGING_FACE', 'HuggingFace', 'huggingface', 'normal'),
    ('TRANSFORMERS', 'Transformers', 'transformers', 'normal'),
    ('LANGCHAIN', 'LangChain', 'langchain', 'normal'),
    ('OPENCV', 'OpenCV', 'opencv', 'normal'),
    ('MLFLOW', 'MLflow', 'mlflow', 'normal'),
    ('XGBOOST', 'XGBoost', 'xgboost', 'normal'),
    ('LIGHTGBM', 'LightGBM', 'lightgbm', 'normal'),
    ('TABLEAU', 'Tableau', 'tableau', 'normal'),
    ('POWER_BI', 'Power BI', 'power bi', 'normal'),
    ('POWER_BI', 'PowerBI', 'powerbi', 'normal'),
    ('LOOKER', 'Looker', 'looker', 'normal'),
    ('APACHE_FLINK', 'Apache Flink', 'apache flink', 'normal'),
    ('APACHE_FLINK', 'Flink', 'flink', 'normal'),
    ('APACHE_ICEBERG', 'Apache Iceberg', 'apache iceberg', 'normal'),
    ('APACHE_ICEBERG', 'Iceberg', 'iceberg', 'normal'),
    ('TRINO', 'Trino', 'trino', 'normal'),
    ('DAGSTER', 'Dagster', 'dagster', 'normal'),
    ('VERTEX_AI', 'Vertex AI', 'vertex ai', 'normal'),
    ('VERTEX_AI', 'Vertex', 'vertex', 'normal'),
    ('TRITON_INFERENCE_SERVER', 'Triton', 'triton', 'normal'),
    ('JAX', 'JAX', 'jax', 'normal'),
    ('CUDA', 'CUDA', 'cuda', 'normal'),
    ('NCCL', 'NCCL', 'nccl', 'normal'),
    ('GITHUB_COPILOT', 'Copilot', 'copilot', 'normal'),
    ('GITHUB_COPILOT', 'GitHub Copilot', 'github copilot', 'normal'),
    ('OPENAI_CODEX', 'Codex', 'codex', 'normal'),
    ('MCP', 'MCP', 'mcp', 'normal'),
    ('MCP', 'Model Context Protocol', 'model context protocol', 'normal'),
    ('SLURM', 'Slurm', 'slurm', 'normal'),
    ('BAZEL', 'Bazel', 'bazel', 'normal'),
    ('GRADLE', 'Gradle', 'gradle', 'normal'),
    ('IOS', 'iOS', 'ios', 'normal'),
    ('ANDROID', 'Android', 'android', 'normal'),
    ('REACT_NATIVE', 'React Native', 'react native', 'normal'),
    ('FLUTTER', 'Flutter', 'flutter', 'normal'),
    ('SWIFTUI', 'SwiftUI', 'swiftui', 'normal'),
    ('XAMARIN', 'Xamarin', 'xamarin', 'normal'),
    ('JETPACK_COMPOSE', 'Jetpack Compose', 'jetpack compose', 'normal'),
    ('RABBITMQ', 'RabbitMQ', 'rabbitmq', 'normal'),
    ('APACHE_PULSAR', 'Apache Pulsar', 'apache pulsar', 'normal'),
    ('APACHE_PULSAR', 'Pulsar', 'pulsar', 'normal'),
    ('ZOOKEEPER', 'Zookeeper', 'zookeeper', 'normal'),
    ('GIT', 'Git', 'git', 'normal'),
    ('GITHUB', 'GitHub', 'github', 'normal'),
    ('GITLAB', 'GitLab', 'gitlab', 'normal'),
    ('JIRA', 'Jira', 'jira', 'normal'),
    ('FIGMA', 'Figma', 'figma', 'normal'),
    ('POSTMAN', 'Postman', 'postman', 'normal'),
    ('CONFLUENCE', 'Confluence', 'confluence', 'normal'),
    ('SALESFORCE', 'Salesforce', 'salesforce', 'normal'),
    ('SALESFORCE', 'Salesforce.com', 'salesforce.com', 'normal'),
    ('SALESFORCE', 'SFDC', 'sfdc', 'normal'),
    ('HUBSPOT', 'HubSpot', 'hubspot', 'normal'),
    ('ZENDESK', 'Zendesk', 'zendesk', 'normal'),
    ('NETSUITE', 'NetSuite', 'netsuite', 'normal'),
    ('VANTA', 'Vanta', 'vanta', 'normal'),
    ('OPENAI', 'OpenAI', 'openai', 'normal'),
    ('ANTHROPIC', 'Anthropic', 'anthropic', 'normal'),
    ('CLAUDE', 'Claude', 'claude', 'normal'),
    ('GPT', 'GPT', 'gpt', 'normal'),
    ('GPT', 'GPT-4', 'gpt-4', 'normal'),
    ('GPT', 'ChatGPT', 'chatgpt', 'normal'),
    ('GEMINI', 'Gemini', 'gemini', 'normal'),
    ('LLAMA', 'Llama', 'llama', 'normal'),
    ('JEST', 'Jest', 'jest', 'normal'),
    ('PYTEST', 'PyTest', 'pytest', 'normal'),
    ('SELENIUM', 'Selenium', 'selenium', 'normal'),
    ('CYPRESS', 'Cypress', 'cypress', 'normal'),
    ('JUNIT', 'JUnit', 'junit', 'normal')
) AS seed(skill_code, alias_text, alias_normalized, match_policy)
JOIN skill s USING (skill_code)
ON CONFLICT (alias_normalized, match_policy) DO UPDATE SET
    skill_id = EXCLUDED.skill_id,
    alias_text = EXCLUDED.alias_text,
    is_active = TRUE;

COMMIT;

-- Expected seed counts: 15 roles, 11 categories, 185 skills, 186 mappings, 254 aliases.
